### ISSUE TITLE
Manipulated Images filename suffix

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-assets#210]
Filenames get a suffix based on the manipulation that happened on them. I remember changing that at some point in the 3.x line so that they were put into folders instead while keeping the original filename, but I guess that missed the transition into 4.x.

Anyhow, the current system even creates filenames such as `WhatsApp-Image-2018-11-24-at-20__FillMaxWzk2MCw2MDBd.17.06-4.jpeg`. I think at least that should be fixed: the suffix should come before the last dot (if anywhere in the filename), not the first one, e.g. becoming `WhatsApp-Image-2018-11-24-at-20.17.06-4__FillMaxWzk2MCw2MDBd.jpeg` instead.

**Comment by maxime-rainville** [comment]
I'm not sure there's an objective way to pick those file name that will please everyone.

If you really need to be able to customise those generated filenames, you might be able to do it by extending `FlysystemAssetStore` and overriding [`getFileID()` ](https://github.com/silverstripe/silverstripe-assets/blob/ba0866a52626266115ffaf8098e1502dafe57905/src/Flysystem/FlysystemAssetStore.php#L846) with your own method.

Then you would be able to inject your own custom AssetStore with something like this:
```yml
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Storage\AssetStore:
    class: JorisDebonnet\YourPrettyGeneratedFilenameAssetStore
    properties:
      PublicFilesystem: '%$League\Flysystem\Filesystem.public'
      ProtectedFilesystem: '%$League\Flysystem\Filesystem.protected'
```

I haven't tried this, so I got no clue if it would actually work.
