### ISSUE TITLE
MigrateFileTask returns wrong paths with legacy_filenames=true

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-assets#257]
Reported by @wilr. 

```
# file path in db and fs
/Users/will/Sites/<project>/vendor/silverstripe/assets/src/Flysystem/FlysystemAssetStore.php:1198:string 'uploads/facilities/wifi3.svg' (length=28)

# file path as worked out by FlysystemAssetStore WRONG
/Users/will/Sites/<project>/vendor/silverstripe/assets/src/Flysystem/FlysystemAssetStore.php:1205:string 'uploads/8abc0f603c/wifi3.svg' (length=28)
object(SilverStripe\Assets\FilenameParsing\ParsedFileID)[1744]
  private 'fileID' => string 'uploads/8abc0f603c/wifi3.svg' (length=28)
  private 'filename' => string 'uploads/wifi3.svg' (length=17)
  private 'variant' => string '' (length=0)
  private 'hash' => string '8abc0f603cc9ce9a10b3c4342428b9a655de89d3' (length=40)

# Of course that path doesn't exist
/Users/will/Sites/<project>/vendor/silverstripe/assets/src/Flysystem/FlysystemAssetStore.php:1207:boolean false
```

Running a pretty recent dev branch of 4.4 (https://gist.github.com/wilr/dee2aa89deedf8911de178f5dfb38dff), but with `legacy_filenames=true`.

He removed file helpers to fix this for him, which shouldn't be necessary:

```
---
Name: kiwirail-migration
After: assetsflysystem
---
SilverStripe\Core\Injector\Injector
 # Define public resolution strategy
 SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.public:
   class: SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy
   properties:
     ResolutionFileIDHelpers:
       - '%$SilverStripe\Assets\FilenameParsing\NaturalFileIDHelper'
       - '%$SilverStripe\Assets\FilenameParsing\LegacyFileIDHelper'
     DefaultFileIDHelper: '%$SilverStripe\Assets\FilenameParsing\NaturalFileIDHelper'
 # Define protected resolution strategy
 SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.protected:
   class: SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy
   properties:
     DefaultFileIDHelper: '%$SilverStripe\Assets\FilenameParsing\NaturalFileIDHelper'
     ResolutionFileIDHelpers:
       - '%$SilverStripe\Assets\FilenameParsing\NaturalFileIDHelper'
     VersionedStage: Stage
```
