### ISSUE TITLE
`Convert()` producing larger image files for avif

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-assets#639]
### Module version(s) affected

2.3.0-beta1

### Description

When converting an image to a different format, the globally set quality setting is used for all formats.

This leads to larger file sizes instead of smaller ones for example for avif images, because avif uses a very different quality scale than other formats. 

For example, a comparable quality avif image would use a quality setting of 50 for a jpq of quality 90.

Webp works ok, because the scale is similar to jpg. But it could also be improved by custom settings.

### How to reproduce

Allow avif files in assets:

```yml
---
Name: app-assets
After:
  - '#assetsfiletypes'
---

SilverStripe\Assets\File:
  file_types:
    avif: 'AVIF Image'
  allowed_extensions:
    - avif
  app_categories:
    image/supported:
      - avif

SilverStripe\Control\HTTP:
  MimeTypes:
    avif: image/avif

SilverStripe\Assets\Storage\DBFile:
  supported_images:
    - 'image/avif'
```

Template:
```
<p>orig: $Image.Fill(200,200)</p>
<p>webp: $Image.Convert('webp').Fill(200,200)</p>
<p>avif: $Image.Convert('avif').Fill(200,200)</p>
```

Result:
![image](https://github.com/user-attachments/assets/78e5d6de-8d33-4a8c-af28-06326b8ca4cf)
Avif image larger do to different quality scale.

### Possible Solution

I suggest defining different quality settings on `InterventionBackend` for the different formats. For example by replacing the `$quality` int with an array, similar to `File::file_types'. Then `InterventionBackend::getQuality()` could check the format and return the corresponding quality for that format.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)
