### ISSUE TITLE
allowed_extensions w/ permission codes

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-assets#64]
Right now `File.allowed_extensions` is a fixed array that applies to all users, anonymous or not. Sometimes, there will be file types that are somewhat risky, on which would want to limit upload rights but not block entirely. For example CMS authors might be able to upload SVGs / HTML files but not the public (if sanitisation wasn't implemented).

This could be supported by allowing a map syntax instead of an array syntax in the config key:

```
SilverStripe\Assets\File:
  allowed_extensions:
    txt: true
    svg: CMS_ACCESS_CMSMain
```
