### ISSUE TITLE
InterventionBackend Quality setting has no effect

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-assets#71]
Quoting the online docs for [Resampled image quality](https://docs.silverstripe.org/en/4/developer_guides/files/images/#resampled-image-quality), the following yaml config (currently using `mysite/_config/config.yml`) should impact resampled images (and I'm assuming all cropped, scaled too - ie: any resampled image):

```
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\InterventionBackend:
    properties:
      Quality: 90
```

This seems to have no effect on resampled images, and even when I test at `Quality: 20` (+ `?flush`) the resampled images are exactly the same physical size & quality as `Quality: 90`, with existing images as well as re-uploaded images.

Are the docs wrong,do I misunderstand the purpose, or is this simply not working? Tested with SilverStripe 4 beta-[1-3].

**Comment by dhensby** [comment]
Gah, this docs are wrong, it should be:

```yml
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    properties:
      Quality: 10
```
